### ISSUE TITLE
License regarding Answers.txt

### ISSUE THREAD

**Issue by C-Bouthoorn** [nayuki/Project-Euler-solutions#10]
Are we allowed to include the Answers.txt file as-is in our own repos, thereby using it as reference material for testing self-written code?

**Comment by nayuki** [comment]
You might as well go ahead, *shrugs*. And perhaps you'll find LuckyToilet's larger collection of answers even more helpful: https://code.google.com/archive/p/projecteuler-solutions/wikis/ProjectEulerSolutions.wiki

**Comment by C-Bouthoorn** [comment]
Thanks! I'll leave your name in-place :smile:
