### ISSUE TITLE
... is it okay to publish my solution elsewhere?

### ISSUE THREAD

**Issue by shaunluttin** [nayuki/Project-Euler-solutions#13]
I've noticed that this repo posts most if not all of the Project Euler answers. That appears to go against the spirit of Project Euler. There is a write up near the bottom of the Project Euler FAQs that talks about this.

**Comment by nayuki** [comment]
The Project Euler problems are [published under](https://projecteuler.net/copyright) the Creative Commons Attribution-NonCommercial-ShareAlike 2.0 UK License. These problems are public and freely shared. My set of PE solutions offer high-quality code and proofs, sharing openly in the same spirit.

For more solutions available online, see:
* (Numbers) https://github.com/luckytoilet/projecteuler-solutions/blob/master/Solutions.md
* (C#) http://www.mathblog.dk/project-euler-solutions/
* (Python) http://www.s-anand.net/euler.html
* (Haskell) https://wiki.haskell.org/Euler_problems
* (Scala) https://github.com/samskivert/euler-scala
* (Rust) https://github.com/gifnksm/ProjectEulerRust/tree/master/src/bin

**Comment by shaunluttin** [comment]
That copyright information is about the problems on the site not their solutions. If I'm not mistaken, the About page FAQ politely asks that people refrain from sharing solutions.

**Comment by nayuki** [comment]
Public solutions are a fair way to respond to public problems.

**Comment by nayuki** [comment]
Public solutions are a fair way to respond to public problems. The cat is out of the bag many times over by many authors, and pursuing secrecy for PE solutions isn't a constructive goal.
