### ISSUE TITLE
[Question] Isn't it too slow to get answer?

### ISSUE THREAD

**Issue by ryanpark91** [nayuki/Project-Euler-solutions#23]
https://github.com/nayuki/Project-Euler-solutions/blob/master/haskell/p010.hs

I did like your code. But it's too slow to get the answer.

**Comment by nayuki** [comment]
Please provide more evidence of your work. What compiler and version did you use? What is your CPU? What execution time did you measure?

On my side of things, I measured 7 seconds on GHC 7.10.3, Intel Core i5-4690 (Haswell) 3.50 GHz.

**Comment by ryanpark91** [comment]
Here is my info.
![image](https://user-images.githubusercontent.com/10189871/64092562-4057ee80-cd90-11e9-91a0-8bac53825100.png)

And Here is my code.
https://github.com/ryanpark91/project-euler-haskell/blob/master/src/Problem_10.hs
