### ISSUE TITLE
Issue with Problem 21  in Python 

### ISSUE THREAD

**Issue by sdban** [nayuki/Project-Euler-solutions#53]
I ran the code for Problem 21 for the first ten numbers. 
```python
def compute():
	# Compute sum of proper divisors for each number
	divisorsum = [0] * 10
	for i in range(1, len(divisorsum)):
		for j in range(i * 2, len(divisorsum), i):
			divisorsum[j] += i
		# Find all amicable pairs within range
	ans = 0
	for i in range(1, len(divisorsum)):
		j = divisorsum[i]
		if j != i and j < len(divisorsum) and divisorsum[j] == i:
			ans += i
	return str(ans)
```
and it doesn't seem to return the right answer. 

For example, for the first 10 numbers the pair (n, d(n)) (where d(n) = sum of proper divisors of n) 
is: 
`[(2, 1), (3, 1), (5, 1), (7, 1), (4, 3), (9, 4), (6, 6), (8, 7), (10, 8)]`
and the answer should be 17.

The code outputs:  `[0, 0, 1, 1, 3, 1, 6, 1, 7, 4]`  for `divisorsum` and 
`0` for the `ans`.

**Comment by nayuki** [comment]
> For example, for the first 10 numbers the pair (n, d(n)) (where d(n) = sum of proper divisors of n)
is:
> [(2, 1), (3, 1), (5, 1), (7, 1), (4, 3), (9, 4), (6, 6), (8, 7), (10, 8)]

In your list of pairs, why is the first number not in ascending order - why is it [2,3,5,7,4,9,6,8,10]?

> and the answer should be 17

I don't see why the answer should be 17. Can you explain?

> The code outputs: [0, 0, 1, 1, 3, 1, 6, 1, 7, 4] for divisorsum and
0 for the ans.

This is correct. The array `divisorsum` is such that for each `i`, `divisorsum[i]` = (sum of proper divisors of i). And `ans` = 0 because there are no [amicable numbers](https://en.wikipedia.org/wiki/Amicable_numbers) strictly less than 10.

**Comment by sdban** [comment]
>In your list of pairs, why is the first number not in ascending order - why is it [2,3,5,7,4,9,6,8,10]?

The list  
>[(2, 1), (3, 1), (5, 1), (7, 1), (4, 3), (9, 4), (6, 6), (8, 7), (10, 8)]
stores the pairs (n, d(n)).  In this output the list is sorted increasing order of d(n) value.  So the prime numbers 2,3,5,7  appear first. 

> I don't see why the answer should be 17. Can you explain?

2+ 3+5+7 = 17 the amicable numbers. 

I think, I understand the source of disagreement. You are not counting 1 as a divisor of a number n (n >1).  As per the problem description 
>For example, the proper divisors of 220 are 1, 2, 4, 5, 10, 11, 20, 22, 44, 55 and 110; therefore d(220) = 284. The proper divisors of 284 are 1, 2, 4, 71 and 142; so d(284) = 220.

it appears that they do consider 1 as a proper divisor and it is included in the count.

**Comment by nayuki** [comment]
> 2+ 3+5+7 = 17 the amicable numbers.

The [problem statement](https://projecteuler.net/problem=21) asks for amicable **pairs**. The numbers {2,3,5,7} are not members of any amicable pairs. In fact, a prime number can never form an amicable pair. There are no amicable numbers less than 10.

> You are not counting 1 as a divisor of a number n

I definitely am counting 1 as a divisor of n. Look at my output array again:

```
divisorsum[0] = 0
divisorsum[1] = 0
divisorsum[2] = 1
divisorsum[3] = 1
divisorsum[4] = 1+2 = 3
divisorsum[5] = 1
divisorsum[6] = 1+2+3 = 6
divisorsum[7] = 1
divisorsum[8] = 1+2+4 = 7
divisorsum[9] = 1+3 = 4
```

**Comment by sdban** [comment]
Ah! I under my mistake.  I don't even know what I was thinking! Thank you for clearing that up! I greatly appreciate it.
