### ISSUE TITLE
Can you keep uploading?

### ISSUE THREAD

**Issue by neurafusionai** [nayuki/Project-Euler-solutions#63]
there is around 900 problems at 2024

**Comment by nayuki** [comment]
I upload solutions when I solve them. I have not been working on Project Euler solutions for years.

> Need help for free?
> 
> Don’t ask me to publish new stuff.
>
> I reserve the right to choose which topics to work on and when to do it. This website is an unpaid hobby of mine, and I am not beholden to requests from random Internet strangers. If you want to see new content, either pay me or make it yourself.

-- https://www.nayuki.io/page/about#contact

**Comment by neurafusionai** [comment]
No, I wanted to know the algorithms applied on, or recommended
books/websites on those algorithms ,  your great work is amazing but only
if you want, if you don't thank you

Thank you for your answer and contribution to the community

Won't ask nothing, well one question yes, what's on the thing that it's
interesting to work on now?2024
