### ISSUE TITLE
Line 4

### ISSUE THREAD

**Issue by Discordanian** [nayuki/Project-Euler-solutions#9]
I was getting a syntax error on line:
`NONPRIME_LAST_DIGITS = {0, 2, 4, 5, 6, 8}`

Which I was able to "correct" by changing to an array notation [0,2...] on line:
` if i == 1 or arr[-1] not in [0,2,4,5,6,8]:`

**Comment by nayuki** [comment]
Citation for the code in question: https://github.com/nayuki/Project-Euler-solutions/blob/fc7b974c2798771eaba938726a48c06b9abc3957/python/p041.py#L12

This line uses Python's set literal notation. It is functionally equivalent to:

    NONPRIME_LAST_DIGITS = set([0, 2, 4, 5, 6, 8])

The set literal syntax is supported in [Python 2.7](https://docs.python.org/2.7/whatsnew/2.7.html#python-3-1-features)+ (year 2010) and [Python 3.0](https://docs.python.org/3/whatsnew/3.0.html#new-syntax)+ (year 2008). I strongly recommend you to upgrade your Python installation.

P.S.: If you are citing the problem as line 4, then you have deleted the copyright notice header.

**Comment by Discordanian** [comment]
I'll have to check the version of python I'm using.  As for line numbers, I'm citing the 4th line of code.  Do people normally count header blocks?  If so, my apologies.  At any rate, thanks for the assist.

**Comment by nayuki** [comment]
Well it's usually easiest to cite the raw line number from the text editor, which would be line 12. Hope the information about Python versions helps. Cheers, Nayuki
